service: fraud-detection
runtime: python310  # The runtime for your Flask app (can be adjusted based on Python version)

instance_class: F1  # Specify the instance class for the app (adjust as needed)

# Automatic scaling configuration
automatic_scaling:
  target_cpu_utilization: 0.65  # Target CPU utilization for scaling
  min_instances: 1  # Minimum number of instances to keep running
  max_instances: 10  # Maximum number of instances to scale to
  max_idle_instances: 5  # Limit idle instances

# Handlers for routing requests (static files and dynamic Flask routes)
handlers:
  - url: /static
    static_dir: static/  # Directory where static files are stored

  - url: /.*  # All other routes handled by Flask
    script: auto  # Automatically handled by the Flask app